name: Deploy deploy-prod to AWS S3
on:
  push:
    branches:
      - deploy/prod
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      # Load environment secrets and create .env file with VITE_ prefix
      - name: Set environment variables
        run: |
          echo "VITE_CORE_API_BASE_URL=${{ secrets.VITE_CORE_API_BASE_URL }}" >> .env
          echo "VITE_API_VERSION=${{ secrets.VITE_API_VERSION }}" >> .env

      - name: Build project
        run: pnpm build

      - name: List dist contents
        run: ls -R dist
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Sync files to S3
        run: |
          aws s3 sync dist s3://qualitybot.ai --acl public-read --delete

    # Configure if you need CloudFront invalidation....
    # - name: Invalidate CloudFront cache
    #   run: |
    #     aws cloudfront create-invalidation --distribution-id your-distribution-id --paths "/*"
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
