name: Deploy cloudfront branch to AWS S3

on:
  push:
    branches:
      - yotlaire-new-branch

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # Debug: Print current directory structure
      - name: Debug - Print directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory structure:"
          ls -R

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Debug: Check if secrets are available
      - name: Debug Secrets Availability
        run: |
          echo "Checking secrets availability..."
          echo "VITE_CORE_API_BASE_URL='${{ secrets.VITE_CORE_API_BASE_URL }}'"
          echo "VITE_API_VERSION='${{ secrets.VITE_API_VERSION }}'"

      # Ensure ai-chatbot directory exists
      - name: Create ai-chatbot directory if not exists
        run: mkdir -p ai-chatbot

      # Create the .env file
      - name: Create .env file
        run: |
          if [ -n "${{ secrets.VITE_CORE_API_BASE_URL }}" ] && [ -n "${{ secrets.VITE_API_VERSION }}" ]; then
            echo "VITE_CORE_API_BASE_URL=${{ secrets.VITE_CORE_API_BASE_URL }}" > ./ai-chatbot/.env
            echo "VITE_API_VERSION=${{ secrets.VITE_API_VERSION }}" >> ./ai-chatbot/.env
          else
            echo "Error: Required secrets are missing."
            exit 1
          fi

      # Verify .env file contents
      - name: Verify .env file contents
        run: |
          echo "Contents of .env file:"
          cat ./ai-chatbot/.env

      # Ensure the .env file persists throughout the workflow
      - name: Ensure .env is still present
        run: |
          if [ -f "./ai-chatbot/.env" ]; then
            echo ".env file exists"
          else
            echo ".env file is missing"
            exit 1
          fi

      # Build the project with environment variables
      - name: Build project
        run: pnpm build
        env:
          VITE_CORE_API_BASE_URL: ${{ secrets.VITE_CORE_API_BASE_URL }}
          VITE_API_VERSION: ${{ secrets.VITE_API_VERSION }}

      # List the directory structure post-build
      - name: List directory structure after build
        run: ls -R

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Sync files to S3
      - name: Sync files to S3
        run: |
          if [ -d "dist" ]; then
            aws s3 sync dist s3://develop-ai-branch --delete
          elif [ -d "ai-chatbot/dist" ]; then
            aws s3 sync ai-chatbot/dist s3://develop-ai-branch --delete
          else
            echo "dist directory not found, cannot sync to S3"
            exit 1
          fi

      # Verify CloudFront Distribution ID
      - name: Verify CloudFront Distribution ID
        run: |
          if [ -z "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
            echo "CLOUDFRONT_DISTRIBUTION_ID is not set"
            exit 1
          else
            echo "CloudFront Distribution ID is '${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}'"
          fi

      # Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
